### ISSUE TITLE
Message level constraints

### ISSUE THREAD

**Issue by ncarenton** [SeriousMa/grpc-protobuf-validation#2]
Hi, are message level constraints handled in the current version? Many thanks!

**Comment by SeriousMa** [comment]
hi  @ncarenton  

sorry ..don't quite understand what you mean...

Can you give me an example?

**Comment by ncarenton** [comment]
Sure @SeriousMa , I believe the current version can handle field level constraint but what if I need to validate something on 2 fields inside a message (e.g.: check that `password` field equals `password_verification` field)

**Comment by SeriousMa** [comment]
I don't think it's suitable for here...
but you can fork and create your own 😊
